/* Configuration for lab1ada generated by Alire */
#ifndef LAB1ADA_CONFIG_H
#define LAB1ADA_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "lab1ada"

#define ALIRE_HOST_OS "windows"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "msys2"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
